In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 


In [3]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.model_selection import train_test_split


In [5]:
X,y=load_iris(return_X_y=True)

In [6]:
X_train ,X_test ,y_train ,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [7]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [8]:
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

